// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hiroto0222/kintai-kanri-web-app/db/sqlc (interfaces: Store)

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	db "github.com/hiroto0222/kintai-kanri-web-app/db/sqlc"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateClockIn mocks base method.
func (m *MockStore) CreateClockIn(arg0 context.Context, arg1 uuid.UUID) (db.ClockIn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClockIn", arg0, arg1)
	ret0, _ := ret[0].(db.ClockIn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateClockIn indicates an expected call of CreateClockIn.
func (mr *MockStoreMockRecorder) CreateClockIn(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClockIn", reflect.TypeOf((*MockStore)(nil).CreateClockIn), arg0, arg1)
}

// CreateClockOut mocks base method.
func (m *MockStore) CreateClockOut(arg0 context.Context, arg1 db.CreateClockOutParams) (db.ClockOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClockOut", arg0, arg1)
	ret0, _ := ret[0].(db.ClockOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateClockOut indicates an expected call of CreateClockOut.
func (mr *MockStoreMockRecorder) CreateClockOut(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClockOut", reflect.TypeOf((*MockStore)(nil).CreateClockOut), arg0, arg1)
}

// CreateEmployee mocks base method.
func (m *MockStore) CreateEmployee(arg0 context.Context, arg1 db.CreateEmployeeParams) (db.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmployee", arg0, arg1)
	ret0, _ := ret[0].(db.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEmployee indicates an expected call of CreateEmployee.
func (mr *MockStoreMockRecorder) CreateEmployee(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmployee", reflect.TypeOf((*MockStore)(nil).CreateEmployee), arg0, arg1)
}

// CreateRole mocks base method.
func (m *MockStore) CreateRole(arg0 context.Context, arg1 string) (db.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRole", arg0, arg1)
	ret0, _ := ret[0].(db.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRole indicates an expected call of CreateRole.
func (mr *MockStoreMockRecorder) CreateRole(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRole", reflect.TypeOf((*MockStore)(nil).CreateRole), arg0, arg1)
}

// CreateSession mocks base method.
func (m *MockStore) CreateSession(arg0 context.Context, arg1 db.CreateSessionParams) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", arg0, arg1)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockStoreMockRecorder) CreateSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockStore)(nil).CreateSession), arg0, arg1)
}

// DeleteClockIn mocks base method.
func (m *MockStore) DeleteClockIn(arg0 context.Context, arg1 int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteClockIn", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteClockIn indicates an expected call of DeleteClockIn.
func (mr *MockStoreMockRecorder) DeleteClockIn(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteClockIn", reflect.TypeOf((*MockStore)(nil).DeleteClockIn), arg0, arg1)
}

// DeleteEmployee mocks base method.
func (m *MockStore) DeleteEmployee(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmployee", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEmployee indicates an expected call of DeleteEmployee.
func (mr *MockStoreMockRecorder) DeleteEmployee(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmployee", reflect.TypeOf((*MockStore)(nil).DeleteEmployee), arg0, arg1)
}

// DeleteRole mocks base method.
func (m *MockStore) DeleteRole(arg0 context.Context, arg1 int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRole", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRole indicates an expected call of DeleteRole.
func (mr *MockStoreMockRecorder) DeleteRole(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRole", reflect.TypeOf((*MockStore)(nil).DeleteRole), arg0, arg1)
}

// GetClockIn mocks base method.
func (m *MockStore) GetClockIn(arg0 context.Context, arg1 int32) (db.ClockIn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClockIn", arg0, arg1)
	ret0, _ := ret[0].(db.ClockIn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClockIn indicates an expected call of GetClockIn.
func (mr *MockStoreMockRecorder) GetClockIn(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClockIn", reflect.TypeOf((*MockStore)(nil).GetClockIn), arg0, arg1)
}

// GetClockOut mocks base method.
func (m *MockStore) GetClockOut(arg0 context.Context, arg1 int32) (db.ClockOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClockOut", arg0, arg1)
	ret0, _ := ret[0].(db.ClockOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClockOut indicates an expected call of GetClockOut.
func (mr *MockStoreMockRecorder) GetClockOut(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClockOut", reflect.TypeOf((*MockStore)(nil).GetClockOut), arg0, arg1)
}

// GetEmployeeByEmail mocks base method.
func (m *MockStore) GetEmployeeByEmail(arg0 context.Context, arg1 string) (db.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeByEmail", arg0, arg1)
	ret0, _ := ret[0].(db.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeByEmail indicates an expected call of GetEmployeeByEmail.
func (mr *MockStoreMockRecorder) GetEmployeeByEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeByEmail", reflect.TypeOf((*MockStore)(nil).GetEmployeeByEmail), arg0, arg1)
}

// GetEmployeeById mocks base method.
func (m *MockStore) GetEmployeeById(arg0 context.Context, arg1 uuid.UUID) (db.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeById", arg0, arg1)
	ret0, _ := ret[0].(db.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeById indicates an expected call of GetEmployeeById.
func (mr *MockStoreMockRecorder) GetEmployeeById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeById", reflect.TypeOf((*MockStore)(nil).GetEmployeeById), arg0, arg1)
}

// GetMostRecentClockIn mocks base method.
func (m *MockStore) GetMostRecentClockIn(arg0 context.Context, arg1 uuid.UUID) (db.ClockIn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMostRecentClockIn", arg0, arg1)
	ret0, _ := ret[0].(db.ClockIn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMostRecentClockIn indicates an expected call of GetMostRecentClockIn.
func (mr *MockStoreMockRecorder) GetMostRecentClockIn(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMostRecentClockIn", reflect.TypeOf((*MockStore)(nil).GetMostRecentClockIn), arg0, arg1)
}

// GetRoleByID mocks base method.
func (m *MockStore) GetRoleByID(arg0 context.Context, arg1 int32) (db.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleByID", arg0, arg1)
	ret0, _ := ret[0].(db.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleByID indicates an expected call of GetRoleByID.
func (mr *MockStoreMockRecorder) GetRoleByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleByID", reflect.TypeOf((*MockStore)(nil).GetRoleByID), arg0, arg1)
}

// GetSession mocks base method.
func (m *MockStore) GetSession(arg0 context.Context, arg1 uuid.UUID) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", arg0, arg1)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockStoreMockRecorder) GetSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockStore)(nil).GetSession), arg0, arg1)
}

// ListClockIns mocks base method.
func (m *MockStore) ListClockIns(arg0 context.Context, arg1 uuid.UUID) ([]db.ClockIn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClockIns", arg0, arg1)
	ret0, _ := ret[0].([]db.ClockIn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClockIns indicates an expected call of ListClockIns.
func (mr *MockStoreMockRecorder) ListClockIns(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClockIns", reflect.TypeOf((*MockStore)(nil).ListClockIns), arg0, arg1)
}

// ListClockInsAndClockOuts mocks base method.
func (m *MockStore) ListClockInsAndClockOuts(arg0 context.Context, arg1 uuid.UUID) ([]db.ListClockInsAndClockOutsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClockInsAndClockOuts", arg0, arg1)
	ret0, _ := ret[0].([]db.ListClockInsAndClockOutsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClockInsAndClockOuts indicates an expected call of ListClockInsAndClockOuts.
func (mr *MockStoreMockRecorder) ListClockInsAndClockOuts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClockInsAndClockOuts", reflect.TypeOf((*MockStore)(nil).ListClockInsAndClockOuts), arg0, arg1)
}

// ListClockOuts mocks base method.
func (m *MockStore) ListClockOuts(arg0 context.Context, arg1 uuid.UUID) ([]db.ClockOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClockOuts", arg0, arg1)
	ret0, _ := ret[0].([]db.ClockOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClockOuts indicates an expected call of ListClockOuts.
func (mr *MockStoreMockRecorder) ListClockOuts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClockOuts", reflect.TypeOf((*MockStore)(nil).ListClockOuts), arg0, arg1)
}

// ListEmployees mocks base method.
func (m *MockStore) ListEmployees(arg0 context.Context, arg1 db.ListEmployeesParams) ([]db.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmployees", arg0, arg1)
	ret0, _ := ret[0].([]db.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEmployees indicates an expected call of ListEmployees.
func (mr *MockStoreMockRecorder) ListEmployees(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmployees", reflect.TypeOf((*MockStore)(nil).ListEmployees), arg0, arg1)
}

// ListRoles mocks base method.
func (m *MockStore) ListRoles(arg0 context.Context, arg1 db.ListRolesParams) ([]db.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoles", arg0, arg1)
	ret0, _ := ret[0].([]db.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoles indicates an expected call of ListRoles.
func (mr *MockStoreMockRecorder) ListRoles(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoles", reflect.TypeOf((*MockStore)(nil).ListRoles), arg0, arg1)
}
