version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./backend/:/app
    tty: true

  postgres:
    image: postgres:13
    container_name: kintai-kanri-postgres
    ports:
      - '5432:5432'
    volumes:
      - progresDB:/var/lib/postgresql/data
    env_file:
      - ./backend/.local.env

volumes:
  progresDB:
