version: '3'
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./backend/:/app
    tty: true
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./frontend/:/app
    tty: true

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_EXTENSIONS: uuid-ossp
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - postgresDB:/var/lib/postgresql/data
    env_file:
      - ./backend/.local.env

volumes:
  postgresDB:
