version: '3'
services:
  postgres:
    image: postgres:13
    container_name: kintai-kanri-postgres
    ports:
      - '5432:5432'
    volumes:
      - progresDB:/var/lib/postgresql/data
    env_file:
      - ./.local.env

volumes:
  progresDB:
