// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"time"
)

type ClockIn struct {
	ID          int32     `json:"id"`
	EmployeeID  int32     `json:"employee_id"`
	ClockInTime time.Time `json:"clock_in_time"`
}

type ClockOut struct {
	ID           int32     `json:"id"`
	EmployeeID   int32     `json:"employee_id"`
	ClockInID    int32     `json:"clock_in_id"`
	ClockOutTime time.Time `json:"clock_out_time"`
}

type Employee struct {
	ID             int32     `json:"id"`
	FirstName      string    `json:"first_name"`
	LastName       string    `json:"last_name"`
	Email          string    `json:"email"`
	Phone          string    `json:"phone"`
	Address        string    `json:"address"`
	HashedPassword string    `json:"hashed_password"`
	RoleID         int32     `json:"role_id"`
	IsAdmin        bool      `json:"is_admin"`
	CreatedAt      time.Time `json:"created_at"`
}

type Role struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Shift struct {
	ID         int32     `json:"id"`
	EmployeeID int32     `json:"employee_id"`
	StartTime  time.Time `json:"start_time"`
	EndTime    time.Time `json:"end_time"`
}
